name: mapkit_snapshotter_flutter
description: A Flutter plugin which provides the MKMapScreenshoter.
version: 1.0.0
homepage: https://github.com/AurityLab/mapkit_snapshotter_flutter
issue_tracker: https://github.com/AurityLab/mapkit_snapshotter_flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MapkitSnapshotterFlutterPlugin
