name: mapkit_snapshotter_flutter
description: A Flutter plugin which provides the MKMapScreenshoter.
version: 0.1.0
homepage: https://github.com/AurityLab/mapkit_snapshotter_flutter
issue_tracker: https://github.com/AurityLab/mapkit_snapshotter_flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.2.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MapkitSnapshotterFlutterPlugin
