name: mapkit_snapshotter_flutter
description: A Flutter plugin which provides the MKMapScreenshoter.
version: 1.0.0
homepage: https://github.com/AurityLab/mapkit_snapshotter_flutter
issue_tracker: https://github.com/AurityLab/mapkit_snapshotter_flutter/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MapkitSnapshotterFlutterPlugin
